# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.1.8
_src_path: gh:epics-containers/ioc-template
description: A Generic IOC for andor3 cameras
git_platform: github.com
github_org: epics-containers
name: ioc-adandor3
repo_uri: git@github.com:epics-containers/ioc-adandor3
rtems: false
